jobs:
- job: macOS
  pool:
    vmImage: macOS-10.13
  steps:
    - bash: |
        set -e
        sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
        brew update
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/sticklerm3/homebrew-pourhouse"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        brew test-bot
      displayName: Run brew test-bot
